# Generated by Django 5.0.6 on 2024-06-08 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0002_book_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birth_name',
            new_name='birth_date',
        ),
    ]
